name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
  
    runs-on: windows-latest  

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
  
    - name: Install .NET 4.8
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 4.8.x

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.0.2
      
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore   
    
    - name: Code sign a file with pfx certificate
      uses: Dana-Prajea/code-sign-action@v4
      with:   
        certificate: "${{ secrets.BASE64_ENCODED_PFX }}" 
        folder:  RevitDBExplorer/sources/bin/Release  
        recursive: false
        password: "${{ secrets.PFX_KEY }}"




    
